name: launch_review
description: A Flutter plugin to reviews in Google Play Store and Apple App Store.
version: 1.1.4
homepage: https://github.com/euferreira/launch_review

environment:  
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.iyaffle.launchreview
        pluginClass: LaunchReviewPlugin
      ios:
        pluginClass: LaunchReviewPlugin

